### PR TITLE
Config with pure python template

### PR DESCRIPTION
**Pull request by icemac**

### CODE REVIEW

**Review by gforcada — APPROVED** [review]

**Comment by gforcada** [comment]
The `py27` status that is waiting needs to be removed from the configuration 👍🏾 

Maybe a script like the [re-enable-actions.py](https://github.com/zopefoundation/meta/blob/master/config/re-enable-actions.py) should be created to deal with this, because as soon as `3.7` is dropped that one will not run and hold PRs, etc 🤔

**Review by dataflake — APPROVED** [review]

**Comment by icemac** [comment]
I have the idea in my mind to automatically creating the list of required jobs but it depends on the actual list of jobs: If there are docs we want them to succeed, if we test on Windows the names of the jobs are different. I'll write a ticket for the Alpine City Sprint.

**Comment by icemac** [comment]
See https://github.com/zopefoundation/meta/issues/191

**Comment by icemac** [comment]
Thank you for reviewing this PR. 😃

**Pull request merged**
