### PR TITLE
Fix deprecation warnings.

### PR DESCRIPTION
**Pull request by jugmac00**
Fix issue #10.

modified:   src/zope/viewlet/manager.py
modified:   src/zope/viewlet/tests.py

### CODE REVIEW

**Review by ale-rt — APPROVED** [review]
ComponentLookupError is in zope.interface since 7 years:
https://github.com/zopefoundation/zope.interface/commit/22f5e01a85f4331141ba782ac96879193f32f59b

**Comment by ale-rt** [comment]
About the test failure, @jugmac00, I would try to copy this code: https://github.com/zopefoundation/zope.server/pull/13/files#diff-562815f32565bb1eb275b2bcce3b2f0fR45

**Comment by jugmac00** [comment]
@ale-rt - Thank you so much for your assistance.

I had and have no failure locally on Python 2.7 - which is kinda odd.

carbon

Update:
I activated the virtual env for Python2, but did make a new buildout, so still Python 3 was used and thus the tests passed. Sorry again!

**Comment by jugmac00** [comment]
Ah sorry, have to redo this pull request tomorrow after a good nights sleep :-(

**Pull request merged**
